# Generated by Django 2.0.7 on 2018-10-24 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feebback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('cno', models.IntegerField(default=10)),
                ('message', models.CharField(max_length=500)),
            ],
        ),
    ]
